services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=grader-db'
      - 'POSTGRES_PASSWORD=graderpass123'
      - 'POSTGRES_USER=illia'
      - 'PGTZ=Europe/Kyiv'
    ports:
      - '5432:5432'